### PR TITLE
RANGER-4916: Before redirect check and remove index.html

### PR DESCRIPTION
**Pull request by prabhjyotsingh**
## What changes were proposed in this pull request?

[RANGER-4916](https://issues.apache.org/jira/browse/RANGER-4916): Before redirect check and remove index.html

Sometimes when the session gets timed-out the page does not redirect to the "login.jsp" page, it's instead gets stuck on "/index.htmllogin.jsp#/policymanager/resource"
Screenshot 2024-08-22 at 8 23 45 AM

## How was this patch tested?

This was tested manually. Steps to repro:
 - Login into ranger UI
 - Either wait for the session to time out or manually delete "RANGERADMINSESSIONID" cookie, the page should get redirected to the right URL

### CODE REVIEW

**Review by RakeshGuptaDev — COMMENTED** [review]
The changes work for the React UI, but the issue persists when switching to the Backbone UI. Could you please address this as well? Thank you.

**Comment by prabhjyotsingh** [comment]
@RakeshGuptaDev sure, I've made those changes.

**Comment by prabhjyotsingh** [comment]
@kumaab @rameeshm @kokosing Can you please help review this PR?

**Comment by prabhjyotsingh** [comment]
@dhavaljrajpara can you please help review?

**Comment by prabhjyotsingh** [comment]
Hi team, I'm just checking in on the status of my pull request. Would you be able to review it soon? 
Would appreciate any feedback or suggestions on this PR.
Thanks!


CC: @fateh288 @mneethiraj  @mehulbparikh @pradeepagrawal8184  @spolavarpau1 @vperiasamy can you please help review?

**Review by ramackri — APPROVED** [review]

**Comment by fimugdha** [comment]
@prabhjyotsingh, tested your changes on a cluster, but it is not working. The redirect url location is not getting created correctly.
Screenshot from 2024-09-18 14-42-32

We already have a jira reported - [RANGER-4213](https://issues.apache.org/jira/browse/RANGER-4213) which is handling this redirect issue and its status code.

Thank you for spending time on providing the fix. We are going with the fix provided in jira - [RANGER-4213](https://issues.apache.org/jira/browse/RANGER-4213)

**Comment by fimugdha** [comment]
cc @mneethiraj

**Comment by prabhjyotsingh** [comment]
Thank you for the review @fimugdha. 
I can confirm https://reviews.apache.org/r/74772/ works as well.

**Pull request closed without merging**
