### PR TITLE
RANGER-5021: Add timeouts to jobs in CI

### PR DESCRIPTION
**Pull request by kumaab**
## What changes were proposed in this pull request?

Add timeouts to jobs in CI

## How was this patch tested?
CI Run 2 successful with timeout of 15 mins.

### CODE REVIEW

**Comment by mneethiraj** [comment]
@kumaab  - would this change result in CI failure when build doesn't complete in 30 minutes?

**Comment by kumaab** [comment]
@mneethiraj 
Yes, that's right. Should we increase the time across different stages?

**Comment by mneethiraj** [comment]
> @mneethiraj Yes, that's right. Should we increase the time across different stages?

I suggest increasing overall timeout to 1 hour, to avoid unnecessary failures due to any slowness in build and testing.

**Comment by kumaab** [comment]
@adoroszlai 
Could you please review this PR, thanks!

**Review by adoroszlai — COMMENTED** [review]
LGTM, most runs seem to be around 20/20/10 minutes for `build-8`, `build-11`, `docker-build`, respectively.

However, there are some runs where `build-8` took significantly more time.  Is such difference expected?

- 60 minutes: https://github.com/apache/ranger/actions/runs/12247100043
- 43 minutes: https://github.com/apache/ranger/actions/runs/12247100740

**Comment by kumaab** [comment]
Yes, with multi-threaded builds `build-8` and `build-11`, runs generally last around 20 mins but sometimes it may run longer may be due to m2 cache not being present and time it takes to populate m2. `docker-build` is faster with caches in place.

CC: @mneethiraj

**Comment by adoroszlai** [comment]
Thanks @kumaab, I didn't notice cache miss.  That should explain it.

**Pull request merged**
