### PR TITLE
RANGER-4857: Upgrade HBASE version to 2.6.0

### PR DESCRIPTION
**Pull request by szucsvillo**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix. Create an issue in ASF JIRA before opening a pull request and
set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. RANGER-XXXX: Fix a typo in YYY))

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

### CODE REVIEW

**Comment by kokosing** [comment]
@mneethiraj this change also look like a good change for handle CVEs

**Comment by bhavikpatel9977** [comment]
@szucsvillo Thank you for working on this. 

Have you validated the Hbase plugin policy enforcement?

**Review by mneethiraj — APPROVED** [review]

**Comment by mneethiraj** [comment]
@szucsvillo - thank you for your contribution. The patch is merged in master and ranger-2.5 branches.

**Comment by mneethiraj** [comment]
> @szucsvillo Thank you for working on this.
> 
> Have you validated the Hbase plugin policy enforcement?

@bhavikpatel9977  - I don't think there is a test to cover this functionality. If you know of any issue with HBase test connection, can we track it via a separate JIRA?

**Comment by bhavikpatel9977** [comment]
AFAIK to service connection will work only after adding below dependency in ranger-plugins/hbase path
-  opentelemetry-api
-  opentelemetry-contex
-  opentelemetry-semconv

**Comment by bhavikpatel9977** [comment]
@szucsvillo  Can you kindly file subsequent Jira to validate the Hbase plugin functionality?

**Pull request closed without merging**
