### PR TITLE
RANGER-3182: Rename Prestosql to Trino

### PR DESCRIPTION
**Pull request by aakashnand**
Refactored prestosql plugin code to work with newly rebranded trino and
fixed missing jars from classpath which are required to work with Trino
version 361

### CODE REVIEW

**Comment by aakashnand** [comment]
@rameeshm Could you please review this? I have migrated the existing presto plugin to the trino plugin and also have fixed some classpath errors. This works with the latest Trino version 361

**Comment by aakashnand** [comment]
@jerryleooo I will need more information to help you. If you have not joined Trino Community Slack I recommend you to join us there and I can help you in slack. 
Recently I also have published a tutorial on how to integrate Ranger and Trino, please check that as well

Integrating Apache Ranger and Trino: https://towardsdatascience.com/integrating-trino-and-apache-ranger-b808f6b96ad8
Trino Slack: https://trino.io/slack.html

**Comment by woowahan-jaehoon** [comment]
I think that adding trino plugin like #106 is best because prestosql cluster cannot be upgraded even if ranger was upgraded.

**Comment by lissali** [comment]
> Hi @aakashnand thanks for the reply, the issues we encountered are resolved, it is not related to this PR so I deleted my comment.
> 
> And now we got another issue, in Presto log we see:
> 
> ```
> 2021-10-12T16:47:28.821+0800    WARN    PolicyRefresher(serviceName=prestodev)-259      org.apache.ranger.admin.client.RangerAdminRESTClient    Error getting Roles. secureMode=false, user=root (auth:SIMPLE), response={"httpStatusCode":401,"statusCode":401,"msgDesc":"Authentication Failed"}, serviceName=prestodev
> 2021-10-12T16:47:58.821+0800    WARN    PolicyRefresher(serviceName=prestodev)-259      org.apache.ranger.admin.client.RangerAdminRESTClient    Error getting Roles. secureMode=false, user=root (auth:SIMPLE), response={"httpStatusCode":401,"statusCode":401,"msgDesc":"Authentication Failed"}, serviceName=prestodev
> 2021-10-12T16:48:23.509+0800    INFO    HttpServerScheduler     org.eclipse.jetty.util.ssl.SslContextFactory    x509=X509@3eac10e4(1,h=[hadoop02-10-165-48-97],w=[]) for Server@c55b55[provider=null,keyStore=file:///etc/presto/presto.hadoop02-10-165-48-97.keystore.jks,trustStore=null]
> 2021-10-12T16:48:28.821+0800    WARN    PolicyRefresher(serviceName=prestodev)-259      org.apache.ranger.admin.client.RangerAdminRESTClient    Error getting Roles. secureMode=false, user=root (auth:SIMPLE), response={"httpStatusCode":401,"statusCode":401,"msgDesc":"Authentication Failed"}, serviceName=prestodev
> 2021-10-12T16:48:58.821+0800    WARN    PolicyRefresher(serviceName=prestodev)-259      org.apache.ranger.admin.client.RangerAdminRESTClient    Error getting Roles. secureMode=false, user=root (auth:SIMPLE), response={"httpStatusCode":401,"statusCode":401,"msgDesc":"Authentication Failed"}, serviceName=prestodev
> ```
> 
> And I guess this is related to the usersync, maybe we missed providing the credentials? If you happen to know what would be the cause can let me know, thanks!

@jerryleooo how did you resolve the issue about 
+ Tue Oct 18 08:28:20 PDT 2022 : Saving lib file: /opt/presto/plugin/ranger/validation-api-2.0.1.Final.jar to /opt/presto/plugin/ranger/.validation-api-2.0.1.Final.jar.20221018082820 ...
Unable to store password in non-plain text format. Error: [Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

I also encountered the same issue when enable presto-plugin.

Thanks  a lot!

**Pull request closed without merging**
