### PR TITLE
Update AWS SDK to 1.12.765

### PR DESCRIPTION
**Pull request by kokosing**
Update AWS SDK to 1.12.765

### CODE REVIEW

**Comment by kokosing** [comment]
@mneethiraj Any chance to land this before release-ing Ranger 2.5.0?

**Comment by mneethiraj** [comment]
@kokosing  - this update will likely not be to be included in Ranger 2.5.0 release; release-candidate #3 is already out for voting. I suggest getting this merged in master branch for 3.0.0 release; if a maintenance release is necessary, 2.5.1 release can be considered.

**Comment by mneethiraj** [comment]
Patch merged via RANGER-4884.

**Comment by kokosing** [comment]
Thank you!

**Pull request closed without merging**
