### PR TITLE
Update hadoop-shaded-guava.version to 1.2.0

### PR DESCRIPTION
**Pull request by kokosing**
Update hadoop-shaded-guava.version to 1.2.0

### CODE REVIEW

**Comment by kokosing** [comment]
@mneethiraj can you please take a look?

**Comment by mneethiraj** [comment]
@kokosing - with this version update, HDFS plugin initialization fails with the following. Can you please review and update the fix? Btw, details on building and running Ranger components in docker containers are available at https://github.com/apache/ranger/tree/master/dev-support/ranger-docker.


```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/base/Preconditions
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:430)
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:443)
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:525)
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:39)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:87)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:41)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.thirdparty.com.google.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more]
Exiting plugin installation
```

**Comment by kokosing** [comment]
Thank you. I will take a look.

**Comment by kokosing** [comment]
This change won't work as hadoop-common@3.3.3 requires version of shaded guava at 1.1.1.

**Pull request closed without merging**
