### PR TITLE
RANGER-3409: remove org.codehaus.jackson ver 1.9 / add com.fasterxml.jackson ver 2.17

### PR DESCRIPTION
**Pull request by nblagodarnyi**
## What changes were proposed in this pull request?

According to https://issues.apache.org/jira/browse/RANGER-3409 all appearances of old org.codehaus.jackson dependencies (ver.1.9.13) were replaced by corresponding new versions from com.fasterxml.jackson. 

## How was this patch tested?
- Locally tested with existing unit/intergration tests in project with different Hadoop versions. 
```
export JAVA_HOME=/path/to/java11;
mvn clean package -Dhadoop.version=3.3.6;  # with latest stable release
mvn clean package; # with default Hadoop version
```
- In physical test environment where Hadoop 3.3.6 / Hive 4 are installed on Ubutnu 20.

### CODE REVIEW

**Comment by sercanCyberVision** [comment]
I have build your branch with Docker option and checked the UI, I see below error in multiple endpoints:
image

For example:
http://<host>:<port>/index.html#/users/usertab
http://<host>:<port>/index.html#/reports/audit/admin

I have seen jackson related serialization issues before which affect UI, you can see the details here:
https://issues.apache.org/jira/browse/RANGER-4225
https://github.com/apache/ranger/pull/252

Could you please check the UI in your end just to make sure?

**Comment by nblagodarnyi** [comment]
Hello Sercan! Thanks for your reply. I didn't manage to reproduce your issue with UI. I used this command to rebuild ranger from my branch and everything works fine in Docker. 
`export RANGER_REBUILD=1 && export DOCKER_MAVEN_BUILD=0 && ./ranger_in_docker up`

image

image

image

**Comment by FerArribas14** [comment]
@nblagodarnyi you are using hadoop 3.3.0. can you rebuild with hadoop version 3.3.6?

Screenshot at Jun 24 15-41-27


I have the same error as @sercanCyberVision

**Comment by nblagodarnyi** [comment]
Hello @FerArribas14! Please refer to the PR description. I've been building/testing it with different Hadoop versions, including 3.3.6. Version built against 3.3.6 now works in our production environment.

**Comment by FerArribas14** [comment]
Hello @nblagodarnyi,

I have built it with hadoop 3.3.6 and java 11 from your branch and it still gives me the same failure. I have the same error as @sercanCyberVision. 

Error

Error2

**Comment by mneethiraj** [comment]
Thank you for the PR. Please note that updates to replace org.codehaus.jackson with com.fasterxml.jackson was merged in [RANGER-4225](https://issues.apache.org/jira/browse/RANGER-4225).

**Pull request closed without merging**
