### PR TITLE
[RANGER-4307] Allow users customize the time interval

### PR DESCRIPTION
**Pull request by zhutong6688**
Modified the UserGroupSyncConfig.java file and added the configuration of user forced custom time synchronization. If enabled, LDAP users can be synchronized according to the user defined time.

## What changes were proposed in this pull request?

RANGER-4307: Added configuration option for ldap: ranger. usersync. ldap. force. sleep time in millisbetweensynccycle. enabled. If enabled (set to true), users will be synchronized according to the time interval set by the user. According to the actual production and usage situation, this demand is often urgently requested by users. this also gives the user more autonomy.

## How was this patch tested?

It was tested in the company's Big data cluster test environment, and later synchronized to the production environment. After rigorous testing, this modification has fully achieved its purpose. The test screenshot is as follows:
image

### CODE REVIEW

**Comment by zhutong6688** [comment]
This PR can greatly improve the production efficiency of enterprises and save a lot of costs for them.

**Comment by qinping416** [comment]
This pull request can improve the production efficiency of enterprises and save costs for enterprises

**Comment by yanghongwei655** [comment]
This PR is very practical and helpful to improve development efficiency, thanks for sharing

**Comment by zachzzq** [comment]
> This PR can greatly improve the production efficiency of enterprises and save a lot of costs for them.
你好 我看你提交修改的代码中引入了新的配置文件属性，但配置文件中并没有这个属性，pr中也找不到。 是我找的有问题吗？

**Comment by zhutong6688** [comment]
@zachzzq 你好，你是apache ranger的负责人吗？这个提交有一定的时间了，没有看到项目负责人的回复。

**Comment by zhutong6688** [comment]
@zachzzq 不过我们在生产上已经用了好久了，对生产的促进也挺大的。

**Comment by zhutong6688** [comment]
您找的有问题，需要把usersync包单独重新打包覆盖之前的，然后按照我上面的做法加上配置就可以了。




| |
朱通
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月05日 01:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [apache/ranger] [RANGER-4307] Allow users customize the time interval (PR #269) |

This PR can greatly improve the production efficiency of enterprises and save a lot of costs for them.
你好 我看你提交修改的代码中引入了新的配置文件属性，但配置文件中并没有这个属性，pr中也找不到。 是我找的有问题吗？

**Pull request merged**
