### PR TITLE
Add Trino v360  support

### PR DESCRIPTION
**Pull request by utk-spartan**

### CODE REVIEW

**Comment by huanghp004** [comment]
hi everyone,I didn't find Trino in version 2.1.0

**Comment by ThoSap** [comment]
Hi, will this be part of the upcoming 2.2.0 release?

**Comment by rameeshm** [comment]
Hi ThoSap, I see that this is still in review stage and won't be possible to include in the release.

**Comment by ThoSap** [comment]
Looking at the past release cycle, does that mean we have to wait another year for Trino support?

**Comment by butaozhang** [comment]
+1 Look forward to merging ranger-rino plugin feat.

**Comment by rgelsi** [comment]
+1 Ranger is the only thing that currently prevents us from migrating to Trino.

**Comment by rameeshm** [comment]
@ThoSap @rgelsi We shall plan doing a minor release may be in 3 months which can include Ranger-3182.
Please comment on the jira and lets work on it to bring it to closure.

**Pull request closed without merging**
