### PR TITLE
Update hadoop to 3.3.4

### PR DESCRIPTION
**Pull request by kokosing**
Update hadoop to 3.3.4

### CODE REVIEW

**Comment by kokosing** [comment]
@mneethiraj Any chance to land this before release-ing Ranger 2.5.0?

**Comment by mneethiraj** [comment]
@kokosing  - this update will likely not be to be included in Ranger 2.5.0 release; release-candidate #3 is already out for voting. I suggest getting this merged in master branch for 3.0.0 release; if a maintenance release is necessary, 2.5.1 release can be considered.

**Comment by mneethiraj** [comment]
@kokosing - later versions of Hadoop, 3.3.5 and 3.3.6, are available for a while. Any reason to not update to the latest version?

**Comment by mneethiraj** [comment]
Patch merged via RANGER-4884.

**Comment by shameersss1** [comment]
@kokosing  @mneethiraj  - Any reason for not upgrading to Hadoop 3.3.5 / 3.3.6 ?
Does this (https://issues.apache.org/jira/browse/HADOOP-18515) have potential to break ranger-kms ?

**Comment by kokosing** [comment]
@shameersss1 There is a follow up for this https://github.com/apache/ranger/pull/370

**Pull request closed without merging**
