### PR TITLE
Update logback to 1.5.6

### PR DESCRIPTION
**Pull request by kokosing**
Update logback to 1.5.6

### CODE REVIEW

**Comment by kokosing** [comment]
@mneethiraj can you please take a look?

**Comment by mneethiraj** [comment]
@kokosing - `mvn clean install` fails in the following tests. Can you please investigate? Also, there was no log file generated in Ranger admin server with this patch. Can you please review this as well? Instructions to build and start Ranger services in docker containers are available under directory dev-support/ranger-docker.

```
[ERROR] Failures:
[ERROR]   TestKMSAudit.testAggregation:104 expected: <true> but was: <false>
[ERROR]   TestKMSAudit.testAggregationUnauth:140 expected: <true> but was: <false>
[ERROR]   TestKMSAudit.testAuditLogFormat:164 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 24, Failures: 3, Errors: 0, Skipped: 0

```

**Comment by mneethiraj** [comment]
@kokosing  - updating slf4j version to 2.0.13 resolved the issue I posted earlier.

logback version 1.4 and above require JDK11 - see https://logback.qos.ch/dependencies.html. Ranger currently supports JDK8, hence updating logback to 1.5.6 wouldn't work. The latest version that can be upgraded to is 1.3.14. Sounds good?

**Comment by mneethiraj** [comment]
Updated patch, to move to logback 1.3.14 is merged in master and ranger-2.5 branches.

**Comment by kokosing** [comment]
Thank you @mneethiraj ❤️

**Comment by kokosing** [comment]
> Ranger currently supports JDK8

@mneethiraj Are you aware of any plans for Ranger project to migrate to java 11? Do you assume it is a big project? Are there any blockers for that endavour?

**Comment by mneethiraj** [comment]
> Are you aware of any plans for Ranger project to migrate to java 11? Do you assume it is a big project? Are there any blockers for that endavour?
I think moving Ranger to JDK 11 wouldn't be much work. However, many services that use Ranger plugin still run on JDK8; hence it may not be the right time to move to a higher JDK version. This should be planned for the next release - 2.6 or 3.0.

**Pull request closed without merging**
