### PR TITLE
RANGER-3290 ArrayIndexOutOfBoundsException if solr is down

### PR DESCRIPTION
**Pull request by asalamon74**
See the details in the jira

### CODE REVIEW

**Comment by asalamon74** [comment]
This travis error looks rather unrelated:

```
Expected feature release number in range of 9 to 17, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

**Review by kulkabhay — APPROVED** [review]

**Comment by asalamon74** [comment]
I fixed some conflicts.

**Review by ramackri — CHANGES_REQUESTED** [review]
This fix got merged into master already
https://github.com/apache/ranger/blob/master/embeddedwebserver/src/main/java/org/apache/ranger/server/tomcat/SolrCollectionBootstrapper.java#L473

**Comment by asalamon74** [comment]
Yes, this is already committed: https://github.com/apache/ranger/commit/bbbc23c005432c715d741e6ea61a9aaddc569845

Closing the pull request

**Pull request closed without merging**
