### PR TITLE
Update commons-compress to 1.26.2

### PR DESCRIPTION
**Pull request by kokosing**
Update commons-compress to 1.26.2

### CODE REVIEW

**Comment by kokosing** [comment]
@mneethiraj Is there a way I can run CI to see if the change is ok. Following https://github.com/apache/ranger/tree/master/dev-support/ranger-docker is working well, but it takes a lot of time and also it is hard to work on multiple changes at once.

**Review by mneethiraj — APPROVED** [review]

**Comment by mneethiraj** [comment]
@kokosing  - thank you for the patch. It is merged in master and ranger-2.5 branches.

**Comment by bhavikpatel9977** [comment]
Is Hbase Service test connection verified?

**Comment by mneethiraj** [comment]
@bhavikpatel9977  - if there is any issue with HBase test connection, let's track it via a separate JIRA.

**Pull request closed without merging**
