### PR TITLE
Ranger-3571: Fix a bug in GrantRevokeRoleRequest.java

### PR DESCRIPTION
**Pull request by AlexaYuqinD**
Fixed a bug in GrantRevokeRoleRequest.java

### CODE REVIEW

**Review by mneethiraj — COMMENTED** [review]
@AlexaYuqinD  - thanks you for the fix. The fix looks good. Can you please file a JIRA at https://issues.apache.org/?

**Comment by AlexaYuqinD** [comment]
@mneethiraj Thanks for reviewing! I've created a JIRA https://issues.apache.org/jira/browse/RANGER-3571

**Comment by AlexaYuqinD** [comment]
> @AlexaYuqinD - thanks you for the fix. The fix looks good. Can you please file a JIRA at https://issues.apache.org/?

@mneethiraj Thanks for reviewing! I've created a JIRA https://issues.apache.org/jira/browse/RANGER-3571

**Comment by mneethiraj** [comment]
Thanks @AlexaYuqinD. Committed to master and ranger-2.3 branches.

**Pull request closed without merging**
